define N = Character('Narrator')
define m = Character("You")
define v = Character("Villain")
define c = Character("Cat")
define T = Character("Mr Steven")
define MC = Character("Claire")
define CAT = Character("Cat")
define it = Character("Cat")

label start:
    scene s1
    m "Another villain on the block ALREADY? Hmph. I already made plans for today. You're really gonna interrupt my splurging on chocolate?"
    v "There's really no need for you to be chasing after me. In the grand scheme of things, what really do these few buildings matter?"
    m "Those buildings you're trying to destroy hold people inside of them and their valuables. I'm not going to let you kill them."
    v "Really, those tortured, poor, dying souls, do you really think they enjoy working in their boring office building? If you think about it I'm really just doing them a favour."
    m "You're insane, and I won't stand for this propaganda!"
    v "You know, it's really cute that you're trying to like, 'stop me' and all, but I have an agenda to get to. Bye!"
    
    scene s2
    N "The new villain sends out a vapor of dark magic, gone when the fumes clear."
    
    scene s3
    "other magical girl" "uhm uhm. Hey, sorry for bothering you.. but was that a new villain on the block?"
    m "Yeah. I kid you not, more villains just keep on coming, it's like a never ending flow of them. This one seems different from the rest, though."
    "Other magical girl" "oh.. Uh really? Uh.. how so? OH NO!.. Is she more dangerous from the rest?! Quick! I'm getting out of here before she finds me!"
    N "The magical girl darts away, frightened. I'm unsure what to make of the situation, but I can't help but wonder why everyone is so hesitant to talk to me, including the most extroverted people I've seen."

    scene s4
    with fade
    N "It's 6:00am."
    N "Battling last night's villain, reporting to headquarters, detransforming - I arrived home pretty late, so all in all, I've slept... 3 hours?" 
    N "I've survived worse."
    N "I sit up in bed, when suddenly my cat leaps into my lap."
    m "Oof!"
    c "[MC]! Great job last night vanquishing that witch last night!"
    N "My magical talking cat, of course."
    N "'Vanquished' isn't the word I'd use. More like 'carelessly let slip through my fingers'. But [CAT] always told me I'm too hard on myself."
    N "I pat [it] on the head placatingly."
    m "It's what I do."
    c "And you do it so well, [MC]! The organisation is so lucky to have you, you know?" 
    m "Ah, well..."
    N "[CAT] has always been a flatterer, but sometimes it's too much, even for me..."
    N "I pick up [CAT] and plop [it] onto the floor, earning me an affronted yowl."
    c "Hey!"
    m "Enough chat! I need to get to school!" 
    m "I've got school council meetings, clubs, maybe more, so..."
    c "Wah?! But it's Friday!!!"
    c "Don't leave me alone for too long!"
    m "(Whiny.)"
    c "And get home in time for... you know...!"
    m "Yeah, yeah, magic, battles, monsters. I know! Don't wait up!"

    scene s5
    with fade
    N "School passes by in a flash of aced quizzes and pleased teachers, like always. I'd consider today to be a success."
    N "Homeroom just finished, marking the end of the school week. Clusters of students gather around their own tables, discussing after-school outings and weekend plans."
    N "I suppress a small stab of envy and pack my planner? maybe? into my backpack."
    N "blah blah clubs aren't on, nothing left to do, etc.."
    m "...something something don't wanna go home yet.."
    N "Maybe there's some council paperwork left to do? Or worksheets that need printing. Or-"

    scene s6
    T "[MC]! You're still here, huh?"
    N "Mr Steven - my chemistry and homeroom teacher - glances around at the steadily emptying classroom, then looks back at me with something approaching pity."
    m "Yep."
    N "Have I ever told you you're my best student?"
    T "Haha! Ha.."
    N "He's joking. Mostly. But he actually has, multiple times. In fact, that same experience tells me that he's using the tone that precedes-"
    T "I have a request- no, an opportunity for you. An enriching, CV-enhancing extracurricular activity."
    m "({i}Yes!{/i})"
    m "Of course! What is it?"
    T "There's a student in one of my classes - a good kid, really, but a bit... troubled. Rough home life. She's been falling behind, and with the mock exams at the end of the year.."
    T "Well. I would hate for her to fail, understand?"
    m "So you want me to tutor her?"
    T "Exactly that. Plenty of transferable skills to be learned from something like this."
    T "What do you say?"
    m "I'll do it."
    T "Perfect! You're doing something very good, [MC]. You should be proud of yourself."
    m "(Everything I do is very good, I like to think.)"
    m "So when will I start seeing this student?"
    T "Ah… Let's see…"
    N "Mr Steven looks at the clock on the wall. His eyes widen."
    T "Right about now, actually!"
    m "Huh? But didn't I just agree now to-"
    T "She's waiting for you in 1.08. Go, go!"
    N "He ushers me towards the door like a whirlwind. I barely manage to grab my backpack before he waves me off cheerily and slides the door shut."

    scene s7
    N "When it comes to taking on responsibilities, it's like I just can't help myself. Better than being lazy, I guess.." 
    N "It's nice to know I have a reputation for reliability, but I feel like I should be at least a bit miffed at Mr Steven's assumption that I'd say yes."
    N "Granted, I immediately {i}did{/i} say yes, but still. Am I that predictable? I'm not a pushover, am I?"

    N "My spiraling is cut off as I find myself in front of room 1.08. The door is cracked open just a sliver, halfway between beckoning and forbidding."
    N "I should be grateful for this, really. I got that excuse I was wishing for - an excuse to forget about my magical girl duties for at least an hour more, barring any world-ending threats."
    N "With the stress of that new villain, a chance to forget for a while is just what I needed."
    N "I slide open the door."

    scene s8
    N "As expected, the classroom is mostly empty."
    N "There is one student, sat near the back by the windows. My gaze lands on my new tutee-"
    
    scene s9
    m "(Oh, you've got to be kidding me.)"
    N "That's unmistakably the new villainess from last night. Unless I'm going crazy, that is absolutely, one-hundred percent her!"
    N "She hasn't noticed me yet. She's just staring out the window. Villainously. Plotting-ly!"
    N "I need to do something. This is my chance. Why can't I move?"
    N "The girl - the witch! - looks up at me, and I stiffen, bracing for the moment when recognition inevitably floods her features."
    N "But it doesn't. Her scowl goes a bit sheepish, actually - embarrassed, maybe."
    v "...I didn't hear you enter."
    N "It sounds like a 'sorry' should follow, but she just leaves it there."
    N "Agh, what do I say? Do I play dumb? Confront her? No, not here, not now - but I need to gauge how much she knows!"
    m "...Right. Um…" 
    m "I'm sorry, have we met before?"
    N "She startles like a stray cat. Again, I brace for something bad."
    v "No."
    v "...I don't think so. I've never…"
    v "We've never spoken."
    N "She avoids my gaze, but she doesn't sound like she's lying. Actually, she sounds pretty affronted at the thought of having interacted with me before... Ouch."
    N "At the very least, I'm pretty confident that she doesn't know I'm the one she was fighting, or else she'd be lunging at me over the desk."
    m "Ah, is that right..? You just have one of those faces, I guess!"
    v "...Indeed."
    m "You might have seen me around running around school before, at least. I'm kind of everywhere, haha."
    N "She nods."
    v "{b}Claire.{/b}"
    N "She says my name like I killed her parents or something… A chill runs through me. Is her default mode of speech just 'supervillain'? Who am I kidding - of course it is."
    m "Yep, that's me!"
    
    menu:
        "Nice to meet you.":
            m "It's nice to finally meet you! I'm [MC]. Nice outfit by the way. For the school dress up competition?"
            v "I know who you are."
            m "My blood runs cold."
            m "She knows. I knew it, she {i}knows{/i} who I am-"
            v "Your activities are plentiful and rather… pervasive. Student council, honour roll, debate club…"
            N "..Oh. She meant my civilian identity. I force myself to breathe normally again."
            v "Must be quite exhausting."
            N "There's something in her voice - not exactly mockery or malice, just… observation. Like she gets it."
            N "Which is ridiculous, because she's a {i}villain.{/i} She doesn't 'get' anything about me."
            N "Her scowl has somehow deepened. Belatedly, I realise she's mirroring the frown that's crept onto my own face. Oops."
            m "I manage! Haha…"
            m "...so. Um."
            N "This is fine. Just act normal."
            m "Mr Steven told me a lot about you. All good things, of course…"
            N "She looks doubtful, but stays silent."
            m "He just mentioned that you need a bit of help with chemistry. Is that right?"

    v "Tch. Perhaps."
    m "Well, you've come to the right person! Err, been sent the right person, I guess."
    N "I reach into my bag and pull out a notebook labeled 'CHEMISTRY' in neat print. Turning to the first page shows an overview of the syllabus, which I place onto the table between us for her to read."
    m "How about this: which topics do you struggle with the most?"
    v "This one."
    m "Uh-huh."
    v "...and that."
    m "Yep."
    v "And that as well… And-"
    m "Right, okay, got it. We've got a lot of work to do."
    N "I pull a chair over to her desk, close enough to see the notebook but far enough to avoid… I don't know, spontaneous villainous combustion.."
    N "Just act normal. It's chemistry. Normal chemistry."
    m "Let's start with the foundations. Atomic structure. Remember anything about electron configuration?"
    v "...Vaguely."
    m "(That's a no, then.)"
    m "Here, look-"
    N "My pen moves quickly, confidently, as I sketch out a quick diagram of an atom. Teaching, at least, is familiar ground. Unlike literally everything else about this."
    m "Electrons fill up the shells in order - closest to the nucleus first. Two in the first shell, then eight, then-"
    v "Why?"
    m "Eh?"
    v "Why do they abide by this… order?"
    N "I blink. That's… a good question. She's thinking, not just accepting it at face value."
    m "Energy levels. Electrons want to be in the lowest energy state possible. That way, they're more stable."
    v "Hmm. {i}Everything{/i} wants to be more stable..."
    N "She says it quietly, almost to herself, as she stares at the diagram with an uncomfortable intensity. There's something about her tone – wistful, bitter."
    N "...We're just talking about electron shells."
    m "That's right. Stability." 
    m "Okay, try drawing the electron configuration for… oxygen. Eight electrons in total."
    N "She picks up her pencil. Grips it tight, too tight. The same way she gripped that staff when she summoned that dark vapor last night."
    N "I swallow hard."
    v "Like so?"
    N "I force myself to look at her work. It's not bad, actually. Her circles aren't the neatest, but the electrons are in the right spots."
    m "Yes! Exactly like that. See? You're getting the hang of it already."
    v "Hmph."
    N "She doesn't exactly smile, but her shoulders relax slightly. Was she nervous about getting it wrong?"
    v "Mind getting me some food, I'm rather hungry, after all"
    m "Uhhh…"
    N "I pull out a protein bar out of my pocket, it's.. Something?"
    m "Here! Dinner is served!"
    v "... Alright. Let's continue."
    N "We work through a few more examples. Sodium. Chlorine. Carbon."
    N "It's so mundane that I almost forget the fact I fought her less than twelve hours ago."
    N "She's really focused now, pencil scratching determinedly across the page, growing more confident by the minute."
    N "I find myself watching her instead of the page. Her hands are delicate, but sure in their movements. Her hair falls across her face as she leans forward."
    N "And from where I'm sitting, I have a perfect view of her profile, sharp, slender, cutting. She squints at the page, tilts her head, catching the late afternoon light just so –"
    N "- and suddenly, deja vu slams into me like a ton of bricks."
    N "This exact angle. Silhouetted against smoke and void. It's exactly the same."
    N "I'm tutoring a supervillain. I'm sitting right next to a girl who vowed to kill me and everything I stand for."
    m "(!)"
    v "{i}What?{/i}"
    m "Huh?"
    N "I'm yanked back to the present, where I'm met with a glower. Her hands hover ever so slightly over her work, like she can't decide between hiding it and shoving it in my face."
    N "Her hackles are raised. Tense. Defensive. As if she's expecting me to do… something. Yell. Maybe worse."
    N "A pit of guilt settles in my stomach."
    
    menu:
        "Sorry, I zoned out…":
            jump zoneout

        "I'm just making sure you're doing it right.":
            jump alr

label zoneout:
    m "S-Sorry! I zoned out. Didn't get enough sleep - you know how it is…"
    v "I suppose I do."
    m "Don't mind me. You're doing perfectly."
    v "Hmph. As I thought."
    v "...Thank you."
    m "It's no problem! No problem at all."
    N "The heavy feeling is washed away by a warm contentment. This is me doing something {i}good.{/i}"
    jump tutoring_end

label alr:
    m "I was just making sure you were doing it right! Sometimes people get a bit lost, you know, and…"
    v "I'm not an infant."
    m "Shoot. Now she looks even more pissed…"
    m "Right. Sorry."
    jump tutoring_end

label tutoring_end:
    N "A brief glance at the clock reveals that it's time for us to wrap this up. In fact, we've gone over by about 20 minutes. Huh."
    m "Alright, we've made really good progress. We'll move onto bonding next time - ionic, covalent-"
    N "The precious little bits of confidence in her expression drain away, and we're back to square one."
    v "This is impossible."
    v "Somehow learning all of this… Passing the final exam…"
    N "She trails off, jaw tight. She sounds… scared."
    m "Hey, don't stress too much. Go easy on yourself."
    N "The words taste hypocritical in my mouth, but I push on dutifully."
    m "I know teachers make it seem like failing these exams is as bad as the end of the world, but it's really, really not."
    N "But instead of bringing relief like I expected, my words only make her even more tense."
    v "..."
    N "Huh? Did I say something wrong?"
    v "That's simply not possible. Consequences will be had."
    v "My parents have made it quite clear that failure is {i}not{/i} an option."
    N "She clutches at her arm, as if remembering a phantom pain. A chill runs through me."
    N "If I'm reading this right - and considering what Mr Steven said about her home life - this is…"
    N "In that moment, I make my decision."
    m "Fine."
    v "I beg your pardon?"
    m "That's fine. You're not going to fail. I won't let you."
    m "You're smart, I know you are - you just need someone to explain things properly. And I can do that. I'm really, really good at that."
    m "So we'll meet, what, three times a week? I'll make you study guides, you'll remember all the content, and you {i}will{/i} pass!"
    N "It's the same tone of voice I use right before I take down a monster. This is just… another kind of obstacle."
    v "...Why?"
    m "Because that's what I do! I help people."
    v "..."
    v "How tedious for you."
    m "I've survived worse!"
    N "The smallest of smiles creeps onto her face, and I can't help but mirror it tenfold."
    N "It feels like something has settled into place. Good or bad, I'm not sure, but…"
    N "I've made a promise. Now I just need to keep it."
    m "Geez, it's getting really late… I'll see you on Monday, okay?"
    N "I'm already halfway out the door, shrugging my cardigan onto my shoulders, when-"
    v "Wait."
    m "Yeah?"
    v "Violet Lai. My name is Violet."
    v "Don't forget it."
    m "Violet..."
    m "It's nice to meet you, Violet"
    v "And you… Claire."

    scene s10
    N "By the time I get home, late afternoon has started to fade into early evening."
    c "Claire! Where have you {i}been?{/i}"
    m "Sorry! One of my professors asked me to tutor someone, and once I said yes they had me start immediately!"
    c ".. You know you don't need to say yes to everything. I thought we had plans too! Anyways, How are they?"
    N "The villain.. Ugh, are they really just a sassy highschool student in disguise? What am I even supposed to do! The org never prepared me for this…"
    N "[CAT] jumps into my lap and I give it a head pat"
    m "Huh? Oh yeah, they're.. Smart. I'm sure they'll pass and stuff. A bit of an attitude though."
    c "you zoned out and now you're not telling me something. I can hear it!"
    m "Uhm.."
    N "[CAT] sends a small growl your way, tail moving erratically in excitement"
    m "Okay okay! They're the new villain. That's it, what I wasn't telling you."
    c "What?! Well, I'm sure you're going to confront them, defeat them, send them to the grave, make them wish they never even glanced at you because you're practically the best in the org-"
    m "What? - No! - No, no, I mean what if I like.. observe them first for information! Not everything is about battles!"
    N "CAT'S THOUGHTS: Huh? That's not like you.."
    c "I mean, if you want, that's your choice."
    N "[CAT] starts dozing off as soon as it finishes it's sentence, and you're left to reflect on your own thoughts"

    scene s11
    N "Why did she mutter 'Everything wants to be more stable'? How did she know my name? I'm really not that popular - Why didn't I confront her? How long do I need to keep up this act?"
    N "These thoughts exhaust me, until I eventually doze off with [CAT] in my arms"
    
    return
